plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace 'com.github.konstantingridasov.resdpi'
    compileSdk = 35
    resourcePrefix = "lib_"
    defaultConfig {
        minSdk = 24
    }

    buildTypes {
        release {
        }
    }
    publishing {
        singleVariant("release") {
            withSourcesJar() 
        }
    }
}

dependencies {
}
afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
//                from components.release
                groupId = 'com.github.KonstantinGridasov'
                artifactId = 'resdpi'
                version = '2.0.1'
            }
        }
    }
}